name: Test wheels

on:
  workflow_dispatch:
    inputs:
      run-id:
        description: 'Use wheels built by dist.yml workflow with this run id (default: use PyPI)'
        required: false
      distributions:
        description: 'Distributions to test (JSON list; default: all)'
        required: false
      python-versions:
        description: 'Python versions to test (JSON list)'
        default: >-
          ['3.10', '3.14']
        required: true
      oss:
        description: 'OSs to test (JSON list; default: all)'
        required: false
  workflow_call:
    inputs:
      run-id:
        type: string
        required: true
      distributions:
        type: string
        required: false
      python-versions:
        type: string
        required: false
      oss:
        type: string
        required: false

jobs:

  tox:
    strategy:
      fail-fast: false
      matrix:
        distribution: >-
          ${{ fromJson(inputs.distributions
                       || '["sagemath-benzene",
                            "sagemath-bliss",
                            "sagemath-brial",
                            "sagemath-buckygen",
                            "sagemath-categories",
                            "sagemath-cddlib",
                            "sagemath-cliquer",
                            "sagemath-cmr",
                            "sagemath-combinat",
                            "sagemath-coxeter3",
                            "sagemath-ecl",
                            "sagemath-eclib",
                            "sagemath-flint",
                            "sagemath-fricas",
                            "sagemath-frobby",
                            "sagemath-gap",
                            "sagemath-gfan",
                            "sagemath-giac",
                            "sagemath-glpk",
                            "sagemath-glucose",
                            "sagemath-graphs",
                            "sagemath-groups",
                            "sagemath-homfly",
                            "sagemath-kenzo",
                            "sagemath-kissat",
                            "sagemath-latte-4ti2",
                            "sagemath-lcalc",
                            "sagemath-libbraiding",
                            "sagemath-libecm",
                            "sagemath-linbox",
                            "sagemath-lrslib",
                            "sagemath-macaulay2",
                            "sagemath-maxima",
                            "sagemath-mcqd",
                            "sagemath-meataxe",
                            "sagemath-modules",
                            "sagemath-msolve",
                            "sagemath-nauty",
                            "sagemath-ntl",
                            "sagemath-palp",
                            "sagemath-pari",
                            "sagemath-planarity",
                            "sagemath-plantri",
                            "sagemath-plot",
                            "sagemath-polyhedra",
                            "sagemath-qepcad",
                            "sagemath-rankwidth",
                            "sagemath-rubiks",
                            "sagemath-schemes",
                            "sagemath-singular",
                            "sagemath-sirocco",
                            "sagemath-standard",
                            "sagemath-standard-no-symbolics",
                            "sagemath-symbolics",
                            "sagemath-sympow",
                            "sagemath-tachyon",
                            "sagemath-tdlib",
                            "sagemath-topcom",
                           ]') }}
        python-version: >-
          ${{ fromJson(inputs.python-versions
                       || '["3.10",
                           ]') }}
        os: >-
          ${{ fromJson(inputs.oss
                       || '["ubuntu-latest",
                            "ubuntu-24.04-arm",
                            "macos-15-intel",
                            "macos-14",
                           ]') }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: "${{ matrix.os }}-*-wheels"
          path: wheelhouse
          merge-multiple: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.inputs.run-id || inputs.run-id }}
        if: github.event.inputs.run-id || inputs.run-id
      - uses: actions/download-artifact@v4
        with:
          pattern: "noarch-wheels*"
          path: wheelhouse
          merge-multiple: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.inputs.run-id || inputs.run-id }}
        if: github.event.inputs.run-id || inputs.run-id
      - uses: actions/download-artifact@v4
        with:
          pattern: "dist*"
          path: wheelhouse
          merge-multiple: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.inputs.run-id || inputs.run-id }}
        if: github.event.inputs.run-id || inputs.run-id
      - uses: actions/setup-python@v5
        id: python
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: |
          pip install tox
      - name: Cache passagemath-conf wheelhouse
        uses: actions/cache@v4
        with:
          path: |
            ~/.sage/sage-*
          key: ci-wheels-${{ matrix.os }}-${{ github.event.inputs.run-id || inputs.run-id }}-${{ matrix.python-version }}
      - name: Run tox
        run: |
          set -x
          python_version=${{ matrix.python-version }}
          python_version_no_dot=${python_version/./}
          pkg=${{ matrix.distribution }}
          pkg_underscore=${pkg//-/_}
          WHEELHOUSE=${GITHUB_WORKSPACE}/wheelhouse
          if [ -d "$WHEELHOUSE" ]; then
              export PIP_FIND_LINKS=file://$WHEELHOUSE
              case $python_version_no_dot in
                  310|311) python_version_abi3=$python_version_no_dot ;;
                  *)       python_version_abi3=312 ;;
              esac
              (set +x; cd "$WHEELHOUSE" && for whl in *.whl *.tar.gz; do
                   case $whl in
                       *$pkg_underscore-*.whl) ;;
                       *musllinux*)            ;;
                       *_i686*)                ;;
                       *-cp$python_version_no_dot-*|*-cp$python_version_abi3-abi3-*|*-none-any*|passagemath_conf-*) echo "${whl%%-*} @ file://$WHEELHOUSE/$whl";;
                   esac;
               done) | tee constraints.txt
              export PIP_CONSTRAINT=${GITHUB_WORKSPACE}/constraints.txt
          else
              mkdir -p $WHEELHOUSE
              pip download -v --only-binary :all: --no-deps -d $WHEELHOUSE pas$pkg
          fi
          # Use passagemath-conf wheelhouse for missing wheels of third-party projects
          case "${{ matrix.os }}" in
              *) export SAGE_CONF_TARGETS="cysignals";;
          esac
          if [ -n "$SAGE_CONF_TARGETS" ]; then
              case "${{ matrix.os }}" in
                  ubuntu*) sudo apt-get update
                           sudo apt-get install binutils make m4 perl flex bison tar bc gcc g++ ca-certificates libbz2-dev bzip2 xz-utils liblzma-dev libffi-dev;;
              esac
              pip install --force-reinstall -v passagemath-conf
              export PIP_FIND_LINKS="$PIP_FIND_LINKS $(sage-config SAGE_SPKG_WHEELS)"
              export PIP_PREFER_BINARY=1
          fi
          case "${{ matrix.os }}" in
              ubuntu*-arm) tag="manylinux*_aarch64";;
              ubuntu*)  tag="manylinux*_x86_64";;
              macos-15-intel) tag="macosx_*_x86_64";;
              macos-14) tag="macosx_*_arm64";;
              windows*-arm) tag="win_arm64";;
              windows*) tag="win_amd64";;
          esac
          # Run tox
          for wheel in "$WHEELHOUSE"/*$pkg_underscore-*-cp$python_version_no_dot-$tag.whl "$WHEELHOUSE"/*$pkg_underscore-*-cp$python_version_abi3-abi3-$tag.whl "$WHEELHOUSE"/*$pkg_underscore-*-py3-none-any.whl; do
            if [ -r "$wheel" ]; then
              cd pkgs/$pkg
              tox_envs=$(tox -l -q| sed 's/sagepython-.*nopypi-norequirements/py'$python_version_no_dot'-norequirements/')
              extras=$(tox -l -q| grep -v notest | sed -E 's/sagepython-.*nopypi-norequirements//;s/^-(.*)/[\1]/;s/-/,/;s/^/'$pkg'/;')
              set +e
              tox -v -v -e $(for env in $tox_envs; do echo -n "$comma$env"; comma=,; done) --installpkg "$wheel"
              status=$?
              set -e
              # Update known test failures
              cd ../..
              pip install passagemath-environment passagemath-repl
              for extra in $extras; do
                  sage --fixdoctests --distribution "$extra" --toxenv py$python_version_no_dot-norequirements --update-known-test-failures || echo "(ignored)"
              done
              git diff || :
              exit $status
            fi
          done
          echo "Wheel missing" >&2
          exit 1
        shell: bash
